build:
  info: "1.0"   
accounts:
  message: "Hi this is Deva."

spring:
  datasource:
    url: jdbc:mysql://89.116.33.142:3306/accountsdb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: DevaWebDev@2306
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://89.116.33.142:8070/eureka/
