build:
  info: "1.2"
cards:
  message: "Hi this is Deva"

spring:
  datasource:
    url: jdbc:mysql://89.116.33.142:3306/cardsdb
    username: root
    password: DevaWebDev@2306
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
