build:
  info: "1.2"
loans:
  message: "Hi this is Deva"

spring:
  datasource:
    url: jdbc:mysql://89.116.33.142:3306/loansdb
    username: root
    password: DevaWebDev@2306
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://89.116.33.142:8070/eureka/
